In [9]:
# 이미지 처리 분야에서 가장 유명한 신경망 모델인 CNN 을 이용하여 더 높은 인식률을 만들어봅니다.
import tensorflow as tf
from PIL import Image
import glob
import numpy as np

image_width = 64
image_height = 64
image_label = []
All_Img = []
#label = np.zeros(3)

In [10]:
image_file_list = glob.glob("./lemon/*.jpg")
for img in image_file_list:
    image_label.append(0)
    image = Image.open(img)
    image = image.resize((image_width, image_height))
   # All_Img.append(np.float32(image))
    image = np.asarray(image, dtype=np.float32)
#    image = image.reshape(1, image_width, image_height, 3)    
#    print(image.shape)
    All_Img.append(image)    
#    All_Img.append(np.asarray( image, dtype="float32" ))
#     print("lemon ::", np.float32(image))

image_file_list = glob.glob("./hanlabong/*.jpg")
for img in image_file_list:
    image_label.append(1)
    image = Image.open(img)
    image = image.resize((image_width, image_height))    
    image = np.asarray(image, dtype=np.float32)
#    image = image.reshape(1, image_width, image_height, 3)
#     print(image.shape)
    All_Img.append(image)    
#    All_Img.append(np.float32(image))
#    All_Img.append(np.asarray( image, dtype="float32" ))
#     print("hanlabong ::", np.float32(image))
image_file_list = glob.glob("./tangerine/*.jpg")
for img in image_file_list:
    image_label.append(2)
    image = Image.open(img)
    image = image.resize((image_width, image_height))    
    image = np.asarray(image, dtype=np.float32)
#    image = image.reshape(1, image_width, image_height, 3)    
#    print(image.shape)
    All_Img.append(image)    
#    All_Img.append(np.float32(image))
#    All_Img.append(np.asarray( image, dtype="float32" ))
#     print("tangerine ::", np.float32(image))
label = np.eye(3)[image_label]    
print(All_Img[1])
print(label)
print(label[250])
print(label[500])

[[[ 63.  77.  86.]
  [ 64.  82.  92.]
  [ 82. 101. 107.]
  ...
  [ 73.  89. 138.]
  [ 71.  87. 136.]
  [ 67.  83. 132.]]

 [[ 77. 100. 108.]
  [ 80. 107. 116.]
  [118. 140. 153.]
  ...
  [ 73.  89. 141.]
  [ 76.  96. 149.]
  [ 81. 101. 162.]]

 [[133. 160. 167.]
  [ 88. 114. 131.]
  [ 90. 108. 130.]
  ...
  [164. 177. 133.]
  [231. 241. 168.]
  [229. 242. 173.]]

 ...

 [[128. 112.  25.]
  [122. 100.  27.]
  [ 90.  74.  15.]
  ...
  [255. 255. 186.]
  [250. 255. 186.]
  [241. 255. 160.]]

 [[143. 125.  63.]
  [129. 108.  25.]
  [ 99.  78.  21.]
  ...
  [255. 255. 133.]
  [249. 252. 121.]
  [244. 229.  74.]]

 [[ 83.  63.  10.]
  [145. 112.   5.]
  [146. 111.   9.]
  ...
  [192. 154.  31.]
  [166. 134.  25.]
  [ 78.  54.   8.]]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[0. 1. 0.]
[0. 0. 1.]


In [ ]:
X = tf.placeholder(tf.float32, [None, image_width, image_height, 3])
Y = tf.placeholder(tf.float32, [None, 3])
keep_prob = tf.placeholder(tf.float32)
print('1')
W1 = tf.Variable(tf.random_normal([3,3,3, 128], stddev=0.01))
L1 = tf.nn.conv2d(X, W1, strides=[1,1,1,1], padding='SAME')
L1 = tf.nn.relu(L1)
L1 = tf.nn.max_pool(L1, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')
print('2')
W2 = tf.Variable(tf.random_normal([3,3,128, 64], stddev=0.01))
L2 = tf.nn.conv2d(L1, W2, strides=[1,1,1,1], padding='SAME')
L2 = tf.nn.relu(L2)
L2 = tf.nn.max_pool(L2, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

W3 = tf.Variable(tf.random_normal([3,3,64, 32], stddev=0.01))
L3 = tf.nn.conv2d(L2, W3, strides=[1,1,1,1], padding='SAME')
L3 = tf.nn.relu(L3)
L3 = tf.nn.max_pool(L3, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

W4 = tf.Variable(tf.random_normal([8*8*32, 32], stddev=0.01))
L4 = tf.reshape(L3, [-1, 8*8*32])
L4 = tf.matmul(L4, W4)
L4 = tf.nn.relu(L4)
L4 = tf.nn.dropout(L4, keep_prob)
print('3')
W5 = tf.Variable(tf.random_normal([32,3], stddev=0.01))
model = tf.matmul(L4, W5)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)
print('4')
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for epoch in range(200):
    _, cost_val = sess.run([optimizer, cost], feed_dict={X: All_Img, Y: label, keep_prob: 0.7})
    print('epoch-', epoch+1, ': ', cost_val)
print('end')


1
2
3
4
epoch- 1 :  1.0984956
epoch- 2 :  1.09661
epoch- 3 :  1.085982
epoch- 4 :  1.0807828
epoch- 5 :  1.0972033
epoch- 6 :  1.0472499
epoch- 7 :  1.0639411
epoch- 8 :  1.0163612
epoch- 9 :  0.97089726
epoch- 10 :  0.9267188
epoch- 11 :  0.8543327
epoch- 12 :  0.7677167
epoch- 13 :  0.7231137
epoch- 14 :  0.76703274
epoch- 15 :  1.0601422
epoch- 16 :  0.6752316
epoch- 17 :  0.9075737
epoch- 18 :  0.64389735
epoch- 19 :  0.7518484
epoch- 20 :  0.7759747
epoch- 21 :  0.71695054
epoch- 22 :  0.6868712
epoch- 23 :  0.70229876
epoch- 24 :  0.72043425
epoch- 25 :  0.6857213
epoch- 26 :  0.64698255
epoch- 27 :  0.6402165
epoch- 28 :  0.65966946
epoch- 29 :  0.6224014
epoch- 30 :  0.590126
epoch- 31 :  0.6171337
epoch- 32 :  0.5938349
epoch- 33 :  0.5710793
epoch- 34 :  0.5936194
epoch- 35 :  0.5513054
epoch- 36 :  0.55050707
epoch- 37 :  0.55877256
epoch- 38 :  0.55299175
epoch- 39 :  0.53958
epoch- 40 :  0.52588755
epoch- 41 :  0.53365993
epoch- 42 :  0.5274517
epoch- 43 :  0.51998407
epoc

In [25]:
image_label = []
All_Img = []
image_file_list = glob.glob("./lemon/*.jpg")
for img in image_file_list:
    image_label.append(0)
    image = Image.open(img)
    image = image.resize((image_width, image_height))
   # All_Img.append(np.float32(image))
    image = np.asarray(image, dtype=np.float32)
#    image = image.reshape(1, image_width, image_height, 3)    
#    print(image.shape)
    All_Img.append(image)    
#    All_Img.append(np.asarray( image, dtype="float32" ))
#     print("lemon ::", np.float32(image))

image_file_list = glob.glob("./hanlabong/*.jpg")
for img in image_file_list:
    image_label.append(1)
    image = Image.open(img)
    image = image.resize((image_width, image_height))    
    image = np.asarray(image, dtype=np.float32)
#    image = image.reshape(1, image_width, image_height, 3)
#     print(image.shape)
    All_Img.append(image)    
#    All_Img.append(np.float32(image))
#    All_Img.append(np.asarray( image, dtype="float32" ))
#     print("hanlabong ::", np.float32(image))
image_file_list = glob.glob("./tangerine/*.jpg")
for img in image_file_list:
    image_label.append(2)
    image = Image.open(img)
    image = image.resize((image_width, image_height))    
    image = np.asarray(image, dtype=np.float32)
#    image = image.reshape(1, image_width, image_height, 3)    
#    print(image.shape)
    All_Img.append(image)    
#    All_Img.append(np.float32(image))
#    All_Img.append(np.asarray( image, dtype="float32" ))
#     print("tangerine ::", np.float32(image))
image_label = np.eye(3)[image_label]    

    
print("Test")

predict = tf.argmax(model, 1)
original = tf.argmax(Y, 1)
is_correct = tf.equal(predict, original)
print('X')
print(sess.run(predict, feed_dict={X: All_Img, keep_prob: 1}))
print('Y')
print(sess.run(original, feed_dict={Y: image_label, keep_prob: 1}))

accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도:',sess.run(accuracy, feed_dict={X: All_Img, Y:image_label, keep_prob:1}))

Test
X
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0
 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0
 2 0 2 0 2 0 0 0 0 2 0 0 0 2 0 2 2 0 0 2 0 0 0 0 2 2 0 2 0 0 0 0 2 0 0 0 0
 2 0 0 0 0 0 0 0 0 0 2 2 2 0 0 2 0 2 2 0 0 2 0 0 0 2 2 0 0 0 0 0 2 0 2 0 0
 2 0 2 2 0 0 0 2 0 0 2 0 0 0 2 0 0 2 0 0 0 0 2 0 2 0 0 0 0 2 0 0 0 2 0 0 2
 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 0 0 2 2 0 0 0 2 2
 2 0 0 0 0 0 0 0 2 0 0 0 0 0 2 0 2 0 2 0 0 0 0 2 0 0 0 0 0 0 0 2 0 2 0 0 0
 0 2 0 0 0 0 0 2 0 2 0 2 0 2 0 0 2 2 2 0 0 2 0 2 0 0 0 0 0 2 0 0 0 0 0 2 0
 2 2 2 0 0 0 2 0 0 0 2 0 0 2 0 0 0 0 0 0 2 0 2 0 2 0 0 2 0 0 0 2 0 0 0 2 0
 0 2 2 2 0 2 0 0 0 0 0 0 2 2 2 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 2 2 0 0 0 0 2
 2 2 0 0 0 0 0 0 2